#!/usr/bin/env node
/** @filedesc CLI: compiles a self-contained USWDS-family Sass entry into a CSS sheet with inlined assets and a sibling class-vocabulary module. With no args, rebuilds this package's own shipped stylesheets. */

import * as sass from 'sass';
import { copyFileSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { findPackageJSON } from 'node:module';

/** Sentinel asset root set as `$theme-font-path` / `$theme-image-path` in uswds-base.scss. */
const ASSET_PREFIX = '@uswds/';

const MEDIA_TYPES = {
    '.woff2': 'font/woff2',
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.gif': 'image/gif',
};

// Both stylesheets land at the package root so `../../<name>.css` reaches them identically from
// `src/<adapter>/index.ts` and `dist/<adapter>/index.js` — the same placement formspec-engine uses for
// `wasm-pkg-runtime/`. A src-aliased consumer (Storybook) would 404 a dist-only path.
const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * A bundler emits `new URL('../uswds-base.css', import.meta.url)` verbatim and never follows the `url()`
 * references inside it, so every `@uswds/...` asset must travel in the file itself as a data URI.
 * Anything already external (`data:`, `http(s):`, or USWDS's own `url("")` `@supports` probe) passes through.
 */
function inlineAssets(css, uswdsDist) {
    const assets = new Map();
    let inlined = 0;
    const out = css.replace(/url\(\s*(['"]?)(.*?)\1\s*\)/g, (whole, _quote, ref) => {
        if (!ref.startsWith(ASSET_PREFIX)) {
            if (ref === '' || ref.startsWith('data:') || /^https?:/.test(ref)) return whole;
            throw new Error(`url(${ref}) escapes the artifact — inline it or drop the rule`);
        }
        const file = join(uswdsDist, ref.slice(ASSET_PREFIX.length));
        if (!assets.has(file)) {
            const type = MEDIA_TYPES[extname(file)];
            if (!type) throw new Error(`no media type registered for ${file}`);
            assets.set(file, `url(data:${type};base64,${readFileSync(file).toString('base64')})`);
        }
        inlined += 1;
        return assets.get(file);
    });
    return { css: out, assetCount: assets.size, inlined };
}

/**
 * Sorted, de-duplicated class names selected anywhere in the compiled CSS. Walks brace depth to isolate
 * selector text from declaration text (and skips at-rule preludes like `@media (...)`) instead of a flat
 * regex, so a class-shaped token can never come from a declaration value — the inlined `url(data:...)`
 * asset bytes included, without needing to strip them separately.
 */
function extractClassVocabulary(css) {
    const classes = new Set();
    let segmentStart = 0;
    for (let i = 0; i < css.length; i++) {
        const ch = css[i];
        if (ch === '{') {
            const selector = css.slice(segmentStart, i).trim();
            if (selector && !selector.startsWith('@')) {
                for (const match of selector.matchAll(/\.-?[_a-zA-Z][-\w]*/g)) {
                    classes.add(match[0].slice(1));
                }
            }
            segmentStart = i + 1;
        } else if (ch === '}') {
            segmentStart = i + 1;
        }
    }
    return [...classes].sort();
}

/**
 * Writes `<outBase>.classes.js` + a `.d.ts` beside it — the same relative-path placement the stylesheet
 * itself resolves via `new URL('../../x', import.meta.url)`, so `RenderAdapter.classVocabulary` can import
 * the artifact from src/ (vitest, Storybook) or dist/ alike. Never hand-edited; regenerated every compile.
 */
function writeClassVocabulary(outBase, classNames) {
    const filedesc = 'Generated by scripts/build-css.mjs — sorted class vocabulary selected in the compiled sheet. Do not hand-edit.';
    writeFileSync(
        `${outBase}.classes.js`,
        `/** @filedesc ${filedesc} */\nexport const classVocabulary = new Set(${JSON.stringify(classNames)});\n`,
    );
    writeFileSync(
        `${outBase}.classes.d.ts`,
        `/** @filedesc ${filedesc} */\nexport declare const classVocabulary: ReadonlySet<string>;\n`,
    );
    return classNames.length;
}

/**
 * Compiles `entryScss` against the USWDS package rooted at `uswdsRoot`, inlining every `@uswds/...` asset
 * reference as a data URI (resolved against `<uswdsRoot>/dist`). No source map — inlining assets shifts
 * every byte offset, so a map of the compiled output would lie. `NodePackageImporter` resolves a `pkg:`
 * specifier (e.g. `@use 'pkg:@formspec-org/adapters/uswds-base' with (...)`), the shape a variant's own
 * entry uses to build on this package's base layer.
 */
function compileLayer(entryScss, uswdsRoot) {
    const compiled = sass.compile(entryScss, {
        style: 'compressed',
        sourceMap: false,
        loadPaths: [join(uswdsRoot, 'packages')],
        importers: [new sass.NodePackageImporter()],
        quietDeps: true,
    });
    return inlineAssets(compiled.css, join(uswdsRoot, 'dist'));
}

/** Compiles `entryScss` to `outCss` and writes the sibling class-vocabulary module next to it. */
function compileAdapterStylesheet(entryScss, outCss, uswdsRoot) {
    const { css, assetCount, inlined } = compileLayer(entryScss, uswdsRoot);
    writeFileSync(outCss, css);
    const classCount = writeClassVocabulary(outCss.replace(/\.css$/, ''), extractClassVocabulary(css));
    return { size: statSync(outCss).size, assetCount, inlined, classCount };
}

/** Locates the `@uswds/uswds` package root visible from `fromUrl` upward — the caller's own install. */
function resolveUswdsRoot(fromUrl) {
    const pkgJson = findPackageJSON('@uswds/uswds', fromUrl);
    if (!pkgJson) throw new Error(`@uswds/uswds not found from ${fromUrl} upward`);
    return dirname(pkgJson);
}

const [entryArg, outArg] = process.argv.slice(2);

if (entryArg && outArg) {
    // Ad-hoc entry (`formspec-adapter-css <entry.scss> <out.css>`): a variant living anywhere — this
    // repo's test fixtures, a downstream consumer's project — resolves `@uswds/uswds` from ITS OWN
    // location upward, not this package's.
    const entryAbs = resolve(entryArg);
    const outAbs = resolve(outArg);
    const uswdsRoot = resolveUswdsRoot(pathToFileURL(entryAbs).href);
    const stats = compileAdapterStylesheet(entryAbs, outAbs, uswdsRoot);
    console.log(
        `${outArg}: ${(stats.size / 1024).toFixed(0)} KB, ${stats.assetCount} assets inlined ` +
            `(${stats.inlined} references), ${stats.classCount} classes`,
    );
} else {
    // Default (`npm run build:css`): rebuild this package's own shipped stylesheets — both USWDS layers
    // (ADR 0063 D-4) plus the Tailwind sheet.
    copyFileSync(
        join(pkgRoot, 'src/tailwind/tailwind-formspec-core.css'),
        join(pkgRoot, 'tailwind-formspec-core.css'),
    );

    const uswdsRoot = resolveUswdsRoot(import.meta.url);
    const base = compileLayer(join(pkgRoot, 'src/uswds/uswds-base.scss'), uswdsRoot);
    writeFileSync(join(pkgRoot, 'uswds-base.css'), base.css);
    const formspec = compileLayer(join(pkgRoot, 'src/uswds/uswds-formspec.scss'), uswdsRoot);
    writeFileSync(join(pkgRoot, 'uswds-formspec.css'), formspec.css);

    // One vocabulary module for the adapter, from the union of both layers (ADR 0063 D-4 / 0064 decision
    // 2): a Theme `cssClass` might select either a base-layer USWDS class or a Formspec rules-layer class,
    // and the renderer checks it against one set.
    const classNames = [...new Set([...extractClassVocabulary(base.css), ...extractClassVocabulary(formspec.css)])].sort();
    const classCount = writeClassVocabulary(join(pkgRoot, 'uswds'), classNames);

    console.log(
        `uswds-base.css: ${(base.css.length / 1024).toFixed(0)} KB, ${base.assetCount} assets inlined (${base.inlined} references)\n` +
            `uswds-formspec.css: ${(formspec.css.length / 1024).toFixed(0)} KB, ${formspec.assetCount} assets inlined (${formspec.inlined} references)\n` +
            `uswds.classes.js: ${classCount} classes (union)`,
    );
}
