/** @filedesc Emit a plan as a readable Playwright spec: one test per thing the documents promise, every expectation written out. */
import type { FormDefinition, LocaleDocument } from '@formspec-org/types';
import type { ExpectedText, Plan, PlanField } from './plan.js';
import { revealSearch, type RevealEngine } from './reveal.js';

export interface EmitOptions {
    /** The page the spec opens; it must mount a `<formspec-render>`. */
    url: string;
    /** What the header says the spec was generated from, and the command that regenerates it. */
    source: string;
    command: string;
    /** The Locale the plan was derived with, for its code and `$ui` strings. */
    locale?: LocaleDocument;
    /** The engine's own answer to "what shows this field", found at emit time; absent means the spec searches at runtime. */
    recipes?: Map<string, Array<{ path: string; value: unknown }> | null>;
    /** The package the emitted spec imports the walk from. */
    from?: string;
}

const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
const text = (t: ExpectedText) => q(t.text);
const baseOf = (path: string) => path.replace(/\[\d+\]/g, '');
/** A title that fits one line of a test report. */
const short = (s: string, max = 90) => (s.length <= max ? s : `${s.slice(0, max - 1).trimEnd()}…`);

/** The literal a field check takes, as source; `extra` rides along in the same object. */
function fieldWantSource(f: PlanField, extra: string[] = []): string {
    const parts = [`label: ${text(f.label)}`];
    if (f.required !== false) parts.push(`required: ${f.required === 'engine' ? "'engine'" : 'true'}`);
    if (f.hint) parts.push(`hint: ${text(f.hint)}`);
    if (f.options?.length) parts.push(`options: [${f.options.map((o) => text(o.label)).join(', ')}]`);
    return `{ ${[...parts, ...extra].join(', ')} }`;
}

function fieldFacts(f: PlanField, shownBy?: Array<{ path: string; value: unknown }> | null, labelOf?: (path: string) => string): string {
    const facts: string[] = [];
    facts.push(f.required === true ? 'required' : f.required === 'engine' ? 'required by rule' : 'optional');
    if (f.options?.length) facts.push(f.options.map((o) => o.label.text).join(' / '));
    if (f.hint) facts.push('with a hint');
    if (f.conditional) {
        if (shownBy?.length) facts.push(`shown when ${shownBy.map((s) => `${labelOf?.(s.path) ?? s.path} = ${JSON.stringify(s.value)}`).join(' and ')}`);
        else facts.push('shown conditionally');
    }
    return facts.join(', ');
}

/**
 * The spec's source. Grouped by top-level group; one test per field (named by its label and what the
 * documents say of it), one per repeat, one for the reading and Tab order over every step, one for the
 * submit summary. Every expectation is written into the file: the walk package supplies only the how.
 */
export function emitSpec(plan: Plan, definition: FormDefinition, options: EmitOptions): string {
    const from = options.from ?? '@formspec-org/walk';
    const code = options.locale?.locale;
    const chrome = Object.fromEntries(Object.entries((options.locale?.strings as Record<string, string> | undefined) ?? {}).filter(([k]) => k.startsWith('$ui.')));
    const labelOf = (path: string) => plan.fields.find((f) => f.path === baseOf(path))?.label.text ?? path;
    const recipes = options.recipes ?? new Map<string, Array<{ path: string; value: unknown }> | null>();
    const lines: string[] = [];
    const push = (s = '') => lines.push(s);

    push('/**');
    push(` * ${plan.title.text} ${definition.version}${code ? ` — ${code} wording` : ''}.`);
    push(` * Generated by ${from} from ${options.source}. Regenerate, don't edit:`);
    push(` *   ${options.command}`);
    push(' *');
    push(' * Every test states what the documents promise; the walk checks the rendered form keeps it, by keyboard');
    push(' * and screen reader (Guidepup\'s virtual reader in the page; FORMSPEC_WALK_SR=os for the OS\'s own).');
    push(' * A failure reads as a list of what contradicted the documents.');
    push(' */');
    push("import { test } from '@playwright/test';");
    push(`import { Walk } from ${q(from)};`);
    push();
    push(`const PAGE = ${q(options.url)};`);
    push(`const open = (page: import('@playwright/test').Page) => Walk.open(page, { url: PAGE${code ? `, locale: ${q(code)}` : ''}${Object.keys(chrome).length ? `, chrome: ${JSON.stringify(chrome, null, 4).replace(/\n/g, '\n    ')}` : ''} });`);
    push();

    // Order over every step.
    push(`test.describe(${q(`${short(plan.title.text)}${code ? ` (${code})` : ''}`)}, () => {`);
    push("    test('every field is read and reached by Tab in Definition order, each group headed', async ({ page }) => {");
    push('        const walk = await open(page);');
    push('        const fields = [');
    for (const f of plan.fields) push(`            { path: ${q(f.path)}, label: ${text(f.label)} },`);
    push('        ];');
    push('        const groups = [');
    for (const g of plan.groups) {
        if (!g.label.text) continue;
        const first = plan.fields.find((f) => f.groups.some((pg) => pg.path === g.path));
        if (first) push(`            { label: ${text(g.label)}, firstField: ${q(first.path)} },`);
    }
    push('        ];');
    push('        for (let step = 0; step < 50; step += 1) {');
    push('            const live = await walk.state();');
    push("            const here = (p: string) => live.filter((f) => f.path.replace(/\\[\\d+\\]/g, '') === p).map((f) => f.path);");
    push('            await walk.readingOrder(fields.flatMap((f) => here(f.path).map((path) => ({ path, label: f.label }))), groups.flatMap((g) => here(g.firstField).slice(0, 1).map((firstField) => ({ label: g.label, firstField }))));');
    push('            await walk.tabOrder(fields.flatMap((f) => here(f.path)));');
    push('            if (!(await walk.nextStep())) break;');
    push('        }');
    push('        walk.expectClean();');
    push('    });');
    push();

    // Fields, in the Definition's own tree: one describe per labelled group, nested as the groups are.
    type Node = { groups: Map<string, { label: string; node: Node }>; fields: PlanField[] };
    const tree: Node = { groups: new Map(), fields: [] };
    for (const f of plan.fields) {
        let at = tree;
        for (const g of f.groups) {
            if (!g.label.text) continue;
            const next = at.groups.get(g.path) ?? { label: g.label.text, node: { groups: new Map(), fields: [] } };
            at.groups.set(g.path, next);
            at = next.node;
        }
        at.fields.push(f);
    }
    const emitNode = (node: Node, indent: string) => {
        const seen = new Map<string, number>();
        for (const f of node.fields) {
            const recipe = recipes.get(f.path);
            // Two fields of one group may share a label ("Hours"); the key tells them apart in the title.
            const n = (seen.get(f.label.text) ?? 0) + 1;
            seen.set(f.label.text, n);
            const title = `${short(f.label.text)}${node.fields.filter((o) => o.label.text === f.label.text).length > 1 ? ` (${f.key})` : ''} — ${fieldFacts(f, recipe, labelOf)}`;
            push(`${indent}test(${q(title)}, async ({ page }) => {`);
            push(`${indent}    const walk = await open(page);`);
            if (f.conditional) {
                const shownBy = recipe?.length ? `[${recipe.map((s) => `{ path: ${q(s.path)}, value: ${JSON.stringify(s.value)} }`).join(', ')}]` : "'engine'";
                push(`${indent}    await walk.reveal(${q(f.path)}, ${fieldWantSource(f, [`shownBy: ${shownBy}`])});`);
            } else {
                push(`${indent}    await walk.field(${q(f.path)}, ${fieldWantSource(f)});`);
            }
            push(`${indent}    walk.expectClean();`);
            push(`${indent}});`);
        }
        for (const [, g] of node.groups) {
            push(`${indent}test.describe(${q(short(g.label))}, () => {`);
            emitNode(g.node, `${indent}    `);
            push(`${indent}});`);
        }
    };
    emitNode(tree, '    ');
    push();

    // Repeats.
    for (const g of plan.groups.filter((g) => g.repeat?.addLabel)) {
        const r = g.repeat!;
        push(`    test(${q(`${short(g.label.text)} — ${r.addLabel!.text}, focus lands in the new row${r.removeLabel ? `, ${r.removeLabel.text}` : ''}`)}, async ({ page }) => {`);
        push('        const walk = await open(page);');
        const firstField = plan.fields.find((f) => f.repeatOf === g.path);
        const recipe = firstField ? recipes.get(firstField.path) : undefined;
        const shownBy = !firstField?.conditional ? '' : recipe?.length ? `, shownBy: [${recipe.map((s) => `{ path: ${q(s.path)}, value: ${JSON.stringify(s.value)} }`).join(', ')}]` : ", shownBy: 'engine'";
        push(`        await walk.repeat(${q(g.path)}, { rowName: ${text(r.rowName)}, addLabel: ${text(r.addLabel!)}${r.removeLabel ? `, removeLabel: ${text(r.removeLabel)}` : ''}${r.maxRepeat !== undefined ? `, maxRepeat: ${r.maxRepeat}` : ''}${firstField ? `, firstField: ${q(firstField.path)}` : ''}${shownBy} });`);
        push('        walk.expectClean();');
        push('    });');
        push();
    }

    // Summary.
    const required = plan.fields.filter((f) => f.required !== false && !f.conditional);
    push("    test('submitting as-is lists every unanswered required question as a link to its answer', async ({ page }) => {");
    push('        const walk = await open(page);');
    push('        await walk.summary([');
    for (const f of required) push(`            { path: ${q(f.path)}, label: ${text(f.label)}${f.requiredMessage ? `, message: ${text(f.requiredMessage)}` : ''} },`);
    push('        ]);');
    push('        walk.expectClean();');
    push('    });');
    push('});');
    push();
    return lines.join('\n');
}

/**
 * What shows each conditional field, asked of an engine at emit time — the values the spec then states
 * outright. Null for a field nothing enumerable reveals; absent from the map when the engine has no
 * instance of it (a repeat with no rows yet).
 */
export function deriveRecipes(engine: RevealEngine, plan: Plan): Map<string, Array<{ path: string; value: unknown }> | null> {
    const optionValues = Object.fromEntries(plan.fields.filter((f) => f.options).map((f) => [f.path, f.options!.map((o) => o.value)]));
    const known = engine.getFieldPaths();
    const out = new Map<string, Array<{ path: string; value: unknown }> | null>();
    for (const f of plan.fields.filter((f) => f.conditional)) {
        const live = known.find((p) => p === f.path) ?? known.filter((p) => baseOf(p) === f.path).sort()[0];
        if (!live) continue;
        const recipe = revealSearch(engine, live, optionValues);
        if (recipe) {
            out.set(f.path, recipe.map(({ path, value }) => ({ path, value })));
            for (const step of [...recipe].reverse()) engine.setValue(step.path, step.previous);
        } else {
            out.set(f.path, null);
        }
    }
    return out;
}
