/** @filedesc USWDS v3 render adapter — CSS-only except DatePicker, which mounts USWDS's own date-picker JS. */
import { deriveAdapter, type RenderAdapter, type StylesheetLayer } from '@formspec-org/webcomponent';
// Generated by scripts/build-css.mjs, sibling to uswds-base.css/uswds-formspec.css (ADR 0064 decision 2) —
// never hand-listed, and a union of both layers. A variant built from uswds-base.scss ships its own pair
// next to its own compiled base sheet (ADR 0063 D-4's README "Variants" section).
import { classVocabulary } from '../../uswds.classes.js';
import { renderTextInput } from './text-input';
import { renderNumberInput } from './number-input';
import { renderRadioGroup } from './radio-group';
import { renderCheckboxGroup } from './checkbox-group';
import { renderSelect } from './select';
import { renderDatePicker } from './date-picker';
import { renderToggle } from './toggle';
import { renderMoneyInput } from './money-input';
import { renderSlider } from './slider';
import { renderRating } from './rating';
import { renderFileUpload } from './file-upload';
import { renderSignature } from './signature';
import { renderWizard } from './wizard';
import { renderTabs } from './tabs';
import { renderActionButton } from './action-button';
import { renderUSWDSGrid } from './layout/grid';
import { renderUSWDSStack } from './layout/stack';
import { renderUSWDSSection } from './layout/page';
import { renderUSWDSDivider } from './layout/divider';
import { renderUSWDSCollapsible } from './layout/collapsible';
import { renderUSWDSPanel } from './layout/panel';
import { renderUSWDSAccordion } from './layout/accordion';
import { renderUSWDSGroup, renderUSWDSRepeatGroup } from './layout/group';
import { renderUSWDSRepeatCards } from './layout/repeat-cards';
import { renderUSWDSModal } from './layout/modal';
import { renderUSWDSPopover } from './layout/popover';
import {
    renderUSWDSHeading,
    renderUSWDSText,
    renderUSWDSCard,
    renderUSWDSAlert,
    renderUSWDSBadge,
    renderUSWDSProgressBar,
    renderUSWDSSummary,
    renderUSWDSValidationSummary,
    renderUSWDSConditionalGroup,
    renderUSWDSDataTable,
} from './display-components';
/**
 * The base layer's presence probe (ADR 0063 D-4): `usa-sr-only` with `position: absolute` is a class every
 * USWDS build defines, ours and an organization's variant alike, so it stands in for "does this page
 * already load USWDS at all."
 */
const USWDS_PRESENT: StylesheetLayer['presentWhen'] = { className: 'usa-sr-only', property: 'position', value: 'absolute' };

/**
 * Formspec's own USWDS rules layer (ADR 0063 D-4) — the render root extends `usa-form`, USWDS's reset scoped
 * to it, field rhythm, help row, rich text, the modal host. Shared unchanged by every variant.
 */
const RULES_LAYER: StylesheetLayer = {
    href: new URL('../../uswds-formspec.css', import.meta.url).href,
    presentWhen: { className: 'formspec-container', property: '--formspec-uswds-rules', value: '1' },
};

/**
 * USWDS v3 adapter for formspec-webcomponent.
 *
 * Emits USWDS markup patterns using `usa-*` CSS classes and owns their presentation: `stylesheets` declares
 * two layers (ADR 0063 D-4) — the design system itself (`uswds-base.css`, self-contained: typefaces and
 * icons inlined) and Formspec's own rules (`uswds-formspec.css`) — each independently skipped when its own
 * presence probe already matches. Hosts import nothing. Every input but DatePicker uses native behavior or
 * `bind()` alone — no USWDS component JavaScript. DatePicker (`date` fields) dynamically imports USWDS's
 * own `usa-date-picker` module when `@uswds/uswds` is installed (optional peer) and falls back to a plain
 * text input otherwise.
 */
export const uswdsAdapter: RenderAdapter = {
    name: 'uswds',
    stylesheets: [
        { href: new URL('../../uswds-base.css', import.meta.url).href, presentWhen: USWDS_PRESENT },
        RULES_LAYER,
    ],
    classVocabulary,
    components: {
        Section: renderUSWDSSection,
        Stack: renderUSWDSStack,
        Grid: renderUSWDSGrid,
        Divider: renderUSWDSDivider,
        Collapsible: renderUSWDSCollapsible,
        Panel: renderUSWDSPanel,
        Accordion: renderUSWDSAccordion,
        Group: renderUSWDSGroup,
        RepeatGroup: renderUSWDSRepeatGroup,
        RepeatCards: renderUSWDSRepeatCards,
        Modal: renderUSWDSModal,
        Popover: renderUSWDSPopover,
        Heading: renderUSWDSHeading,
        Text: renderUSWDSText,
        Card: renderUSWDSCard,
        Alert: renderUSWDSAlert,
        Badge: renderUSWDSBadge,
        ProgressBar: renderUSWDSProgressBar,
        Summary: renderUSWDSSummary,
        ValidationSummary: renderUSWDSValidationSummary,
        ConditionalGroup: renderUSWDSConditionalGroup,
        DataTable: renderUSWDSDataTable,
        TextInput: renderTextInput,
        NumberInput: renderNumberInput,
        RadioGroup: renderRadioGroup,
        CheckboxGroup: renderCheckboxGroup,
        Select: renderSelect,
        DatePicker: renderDatePicker,
        Toggle: renderToggle,
        MoneyInput: renderMoneyInput,
        Slider: renderSlider,
        Rating: renderRating,
        FileUpload: renderFileUpload,
        Signature: renderSignature,
        Wizard: renderWizard,
        Tabs: renderTabs,
        ActionButton: renderActionButton,
    },
};

export interface UswdsVariantOptions {
    /** The name the Theme's `adapter` names, e.g. `"uswds-nj"`. */
    name: string;
    /** Absolute URL of the organization's compiled USWDS (`formspec-adapter-css` output of a `uswds-base.scss` entry). */
    stylesheet: string;
    /** The class vocabulary the CLI wrote beside that sheet. Omit it and Theme classes go unchecked. */
    classVocabulary?: ReadonlySet<string>;
}

/**
 * An organization's USWDS as an adapter (ADR 0064 decision 1): the USWDS components, its own compiled sheet as
 * the base layer, and this package's rules layer unchanged. The vocabulary is the variant's merged with this
 * adapter's, since the variant's own compile never carries the rules layer's classes.
 */
export function uswdsVariant({ name, stylesheet, classVocabulary: variantVocabulary }: UswdsVariantOptions): RenderAdapter {
    return deriveAdapter(uswdsAdapter, {
        name,
        stylesheets: [{ href: stylesheet, presentWhen: USWDS_PRESENT }, RULES_LAYER],
        classVocabulary: variantVocabulary && new Set([...variantVocabulary, ...classVocabulary]),
    });
}
